version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/images/prow-tests/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "docker"
    directory: "/images/prow-tests/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "go1.19.*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
